source "https://rubygems.org"

gem "rails", "~> 7.2.0"
gem "blazer", "3.5.1"
gem "puma"
gem "tzinfo-data"
gem "sprockets-rails"

# data sources
gem "pg"

# publish Blazer's Slack notifications via SNS (ECS task has no direct internet egress)
gem "aws-sdk-sns"

# anomaly detection and forecasting
gem "anomaly_detection"
gem "prophet-rb"
gem "trend"

gem "nokogiri"

# Authentication via Devise and Google OAuth
gem "dotenv-rails"
gem "devise"
gem "omniauth"
gem "omniauth-google-oauth2"

group :development, :test do
  gem "debug", require: false
  gem "rspec-rails", require: false
  gem "standard", require: false
end
