name: Create Manifests Release PR

on:
  workflow_run:
    workflows: ["Docker image build and push"]
    branches: [main]
    types: 
      - completed

permissions:
  id-token: write
  contents: write

jobs:
  create-release-pr:
    runs-on: ubuntu-latest
    # Only run if the triggering workflow (docker build and push) was successful
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Checkout
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
        with:
          ref: ${{ github.event.workflow_run.head_branch }}

      - name: my-app-install token
        id: notify-pr-bot
        uses: getsentry/action-github-app-token@38a3ce582e170ddfe8789f509597c6944f2292a9 # v1.0.6
        with:
          app_id: ${{ secrets.NOTIFY_PR_BOT_APP_ID }}
          private_key: ${{ secrets.NOTIFY_PR_BOT_PRIVATE_KEY }}

      - uses: cds-snc/notification-pr-bot@main
        env:
          TOKEN: ${{ steps.notify-pr-bot.outputs.token }}
