name: Docker image build

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main

jobs:
  docker-build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - lambda: blazer
            folder: blazer
          - lambda: google-cidr
            folder: google-cidr
          - lambda: heartbeat
            folder: heartbeat
          - lambda: system_status
            folder: system_status
          - lambda: ses_to_sqs_email_callbacks
            folder: sesemailcallbacks

    steps:
      - name: Checkout
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0

      - uses: dorny/paths-filter@7267a8516b6f92bdb098633497bad573efdbf271 # v2.12.0
        id: changes
        with:
          filters: |
            lambda:
              - '${{ matrix.lambda }}/**'
              - '.github/workflows/docker-build.yml'

      - name: Build Docker image
        if: steps.changes.outputs.lambda == 'true'
        working-directory: ${{ matrix.folder }}
        run: |
          echo "Current working directory: $(pwd)"
          echo "Matrix Lambda: ${{ matrix.lambda }}"
          make docker
